@startuml
class User {
    + id : int
    + roleid : id
    + name : String
     . . . . . . . . .
    Getter & Setter
}


class UserService {
    + login()
}

interface IUserService {
    + login()
}

UserService --|> IUserService
User ..> IUserService : <<use>>


@enduml
