@startuml

actor Staff
participant StaffInteraction as inter
participant StaffCordinator as cor
participant ValidationService as ser


Staff -> inter --++: Fill information
inter -> cor --++: Request
cor -> ser --++ : Request
ser -> ser ++--: Validate
ser --> cor --++ : Success
cor -->inter --++: Refractor main screen
inter -->Staff --++: Refractor main screen


@enduml
