@startuml

actor Staff
participant StaffInteraction as inter
participant StaffCordinator as cor
participant ValidationService as ser


Staff -> inter --++: Fill information
inter -> cor --++: Request
cor -> ser --++ : Request
ser -> ser ++--: Validate
ser --> cor --++ : Fail
cor -->inter --++: Fail
inter -->Staff --++: Fail message 


@enduml
