@startuml
actor       Staff       as staff
participant StaffInteraction as interact
participant StaffCoordinate as coor
participant UserService as service
database    Database    as db

staff -> interact ++: 1. Input fields

staff -> interact  : 2. Click "Login"

interact -> coor --++: 3.validate input

alt fail case
    coor --> interact --++: 4.return msg
    interact --> staff --: 5. display msg fail
else success case
     coor -> service --++: 4.login()
     service -> db --++: 5.query
     db --> service --++: 6.return user
     alt user null 
        service --> coor --++: 7.return msg
        coor --> interact --++: 8.return msg
        interact --> staff --: 9. display msg reinput
     else user not null
        service --> coor --++: 7.return user
        coor --> interact --++: 8.return user
        interact   --> staff --: 9. redirect to home page
     end
     
end


@enduml
