@startuml

actor       Admin
participant LoginPage
participant LoginController
participant EditController
participant UserDAO
database DB

    Admin -> LoginPage  ++: 1.Input Adminname and password
    Admin -> LoginPage  --: 2.Click Login
    LoginPage -> LoginController --++: 3.sendRequest()
    LoginController -> UserDAO --++: 4.getAdmin()
    UserDAO -> DB --++ : 5.Query in DB
    DB --> UserDAO --++: 6.return Admin
    UserDAO --> LoginController --++: 7.return Admin
    LoginController -> EditController --++: 8.doGet()
    EditController --> Admin --++: 9.sendDirect to Admin Profile Page


@enduml