@startuml

actor       Admin
participant AuthorManagementPage
participant AuthorController
participant AuthorDAO
database DB


Admin -> AuthorController  --++: 1.Click on "Authors Management" title
AuthorController -> AuthorDAO ++: 2.getAllAuthor()
AuthorController -> AuthorDAO --: 3.getAllAdmin()
AuthorDAO -> DB --++ : 4.Query in DB
DB --> AuthorDAO --++: 5.return Author List
AuthorDAO --> AuthorController --++: 6.return Author List
AuthorController -> AuthorDAO --++: 7.getByPage()
AuthorDAO --> AuthorController --++: 8.return Author List
AuthorController --> AuthorManagementPage --: 9.dispatch

@enduml