@startuml

actor       Admin
participant AuthorManagementPage
participant AuthorController
participant AuthorDAO
database DB
alt
    Admin -> AuthorManagementPage  ++: 1.Input new author name
    Admin -> AuthorManagementPage  --: 2.Press button
    AuthorManagementPage -> AuthorController  --++: 3.doPost()
    AuthorController -> AuthorDAO --++: 4.updateAu()
    AuthorDAO -> DB --++ : 5.Query in DB
    DB --> AuthorDAO --++: 6.return
    AuthorDAO --> AuthorController --++: 7.return
end
AuthorController -> AuthorDAO ++: 8.getAllAuthor()
AuthorController -> AuthorDAO --: 9.getAllAdmin()
AuthorDAO -> DB --++ : 8.Query in DB
DB --> AuthorDAO --++: 9.return Author List
AuthorDAO --> AuthorController --: 10.return Author List
alt
    group IF
        Admin -> AuthorManagementPage  --++: 1.Input in right search box
        Admin -> AuthorManagementPage  --: 2.Press Enter
        AuthorManagementPage -> AuthorController  --++: 3.doPost()
        AuthorController -> AuthorDAO --++: 4.searchByAname()
        AuthorDAO -> DB --++ : 5.Query in DB
    end
    group IF
        Admin -> AuthorManagementPage  --++: 1.Input in left search box
        Admin -> AuthorManagementPage  --: 2.Press Enter
        AuthorManagementPage -> AuthorController  --++: 3.doPost()
        AuthorController -> AuthorDAO --++: 4.searchByUname()
        AuthorDAO -> DB -- : 5.Query in DB
    end
    DB --> AuthorDAO --++: 9.return Author List
    AuthorDAO --> AuthorController --: 10.return Author List
end


AuthorController -> AuthorDAO --++: 11.getByPage()
AuthorDAO --> AuthorController --++: 12.return Author List
AuthorController --> AuthorManagementPage --: 13.dispatch


@enduml