@startuml

actor       Admin
participant DashBoardPage
participant DashBoard
participant AuthorDAO
participant UserDAO
participant BookDAO
participant CommentDAO


database DB


Admin -> DashBoard  --++: Click on "Dash Board" title
DashBoard -> AuthorDAO ++: getAllAuthor()
DashBoard -> AuthorDAO : getAllUser()
DashBoard -> AuthorDAO : getNumQuater()
DashBoard -> AuthorDAO : getNumYear()
AuthorDAO -> DB --++ : Query in DB

DashBoard -> UserDAO ++: getAllUser()
UserDAO -> DB -- : Query in DB

DashBoard -> BookDAO ++: count()
BookDAO -> DB -- : Query in DB

DashBoard -> CommentDAO --++: count()
CommentDAO -> DB  --: Query in DB


DB --> AuthorDAO : return Author List
DB --> AuthorDAO : return Integer List

AuthorDAO --> DashBoard ++: return Author List
AuthorDAO --> DashBoard --: return Integer List

DB --> UserDAO ++: return User List
UserDAO --> DashBoard --: return User List

DB --> BookDAO ++: return int 
BookDAO --> DashBoard --: return int 
DB --> CommentDAO ++: return int 
CommentDAO --> DashBoard --: return int 

DashBoard --> DashBoardPage --: dispatch

@enduml