@startuml

actor       Admin
participant ADprofilePage
participant EditController
participant UserDAO
database DB

Admin -> ADprofilePage  ++: 1.Input profile
Admin -> ADprofilePage  --: 2.Click Update
ADprofilePage -> EditController --++: 3.doPost()
EditController -> EditController : 4.checkDuplicate()
alt

    EditController -> UserDAO --++: 5.editProfile()
    UserDAO -> DB --++ : 6.Query in DB
    DB --> UserDAO --++: 7.return
    UserDAO --> EditController --++: 7.return
    EditController --> ADprofilePage  : 8.sendDirect and notice Successfully
else
    EditController --> ADprofilePage --: 8.sendDirect
end



@enduml