@startuml

actor       Admin
participant TicketScreen
participant TickController
participant TicketDAO
participant UserDAO
database DB

Admin -> TicketScreen   ++: 1.Click Button
TicketScreen -> TickController   --++: 2.doPost()
TickController -> TicketDAO --++: 3.setStatus()
TicketDAO -> DB --++ : 4.Query in DB
DB --> TicketDAO --++: 5.return
TicketDAO --> TickController --++: 6.return
alt Pass
    TickController -> TicketDAO --++: getRP()
    TicketDAO -> DB --++ : Query in DB
    DB --> TicketDAO --++: return Ticket
    TicketDAO --> TickController --++: return Ticket
    TickController -> UserDAO --++: editRank()
    UserDAO -> DB --++ : Query in DB
    DB --> UserDAO --++: return 
    UserDAO --> TickController --++: return 
end
TickController -> TickController : doGet()
TickController --> TicketScreen  --: 8.dispatch


@enduml