@startuml

actor       Admin
participant TicketScreen
participant TickController
participant TicketDAO
database DB

Admin -> TickController   ++: 1.Input mail icon
TickController -> TicketDAO --++: 2.getAll()
TicketDAO -> DB --++ : 3.Query in DB
DB --> TicketDAO --++: 4.return Ticket list
TicketDAO --> TickController --++: 5.return Ticket list
TickController -> TicketDAO --++: 6.getByPage()
TicketDAO --> TickController --++: 7.return Ticket list
TickController --> TicketScreen  --: 8.dispatch


@enduml