@startuml

actor       Admin
participant TicketScreen
participant UserActionController
participant TicketDAO
participant UserDAO
participant TransactionDAO
database DB

Admin -> TicketScreen   ++: 1.Click on user id
TicketScreen -> UserActionController   --++: 2.doGet()
UserActionController -> UserDAO --++: 3.getUser()
UserDAO -> DB --++ : 4.Query in DB
DB --> UserDAO --++: 5.return User
UserDAO --> UserActionController --++: 6.return User

UserActionController -> TransactionDAO --++: 7.getTransactionList()
TransactionDAO -> DB --++ : 8.Query in DB
DB --> TransactionDAO --++: 9.return Transaction List
TransactionDAO --> UserActionController --++: 10.return Transaction List
UserActionController -> TransactionDAO --++: 11.getByPage()
TransactionDAO --> UserActionController --++: 12.return Transaction List

UserActionController -> UserDAO --++: 13.getAction()
UserDAO -> DB --++ : 14.Query in DB
DB --> UserDAO --++: 15.return ticket List
UserDAO --> UserActionController --++: 16.return ticket List
UserActionController -> UserDAO --++: 17.getByPage()
UserDAO --> UserActionController --++: 18.return ticket List
UserActionController --> TicketScreen  --: 19.dispatch


@enduml