@startuml

actor       User
participant SupportPage
participant OnReadController
participant SupportController
participant TicketDAO
database DB

alt
    User -> SupportPage  ++: 1.Click V button
    SupportPage -> OnReadController  --++: 2.doGet()
    OnReadController -> TicketDAO --++: 3.read()
    TicketDAO -> DB --++ : 4.Query in DB
end
alt
    User -> SupportPage  ++: 1.Click Read All button
    SupportPage -> OnReadController  --++: 2.doGet()
    OnReadController -> TicketDAO --++: 3.readAll()
    TicketDAO -> DB -- : 4.Query in DB
end

DB --> TicketDAO --++: 5.return 
TicketDAO --> OnReadController --++: 6.return
OnReadController -> SupportController --++: 7.doGet()
SupportController --> SupportPage --: 8.dispatch


@enduml