@startuml

actor       User
participant SupportPage
participant SupportController
participant TicketDAO
participant UserDAO
database DB

User -> SupportPage  ++: 1.Send Ticket
SupportPage -> SupportController  --++: 2.doPost()
SupportController -> UserDAO --++: 3.isVIP()
UserDAO -> DB --++ : 4.Query in DB
DB --> UserDAO --++: 5.return
UserDAO --> SupportController --++: 6.return

alt isVip
    SupportController -> TicketDAO --++: passReport()
    TicketDAO -> DB --++ : Query in DB
    DB --> TicketDAO --++: return
    TicketDAO --> SupportController --++: return
    SupportController -> UserDAO --++: editRank()
    UserDAO -> DB --++: Query in DB
    DB --> UserDAO --++: return
    UserDAO --> SupportController --: return
end
alt isnotVip
    SupportController -> TicketDAO --++: passReport()
    TicketDAO -> DB --++ : Query in DB
    DB --> TicketDAO --++: return
    TicketDAO --> SupportController --: return
end

SupportController -> SupportController ++: doGet()
SupportController --> SupportPage -- :dispatch

@enduml