@startuml

actor       Admin
participant AdminManagementPage
participant UserController
participant UserDAO
database DB
alt
    Admin -> AdminManagementPage  ++: 1.Input in Search Box
    Admin -> AdminManagementPage  --: 1.Press Enter
    AdminManagementPage -> UserController  --++: 2.doPost()
    UserController -> UserDAO --++: 3.searchByName()
    UserDAO -> DB --++ : 4.Query in DB
    DB --> UserDAO --++: 5.return Admin List
    UserDAO --> UserController --: 6.return Admin List
end
alt
    group IF
        Admin -> AdminManagementPage  --++: 1.Click on "Up" or "Down" button
        AdminManagementPage -> UserController  --++: 2.doPost()
        UserController -> UserDAO --++: 3.editRank()
        UserDAO -> DB --++: 4.Query in DB
    end
    group IF
        Admin -> AdminManagementPage  --++: 1.Click on "Disable" button
        AdminManagementPage -> UserController  --++: 2.doPost()
        UserController -> UserDAO --++: 3.disableAdmin()
        UserDAO -> DB -- : 4.Query in DB
    end
    DB --> UserDAO --++: 5.return
    UserDAO --> UserController --++: 6.return
    UserController -> UserDAO --++: 7.getByAccess()
    UserDAO -> DB --++ : 8.Query in DB
    DB --> UserDAO --++: 9.return Admin List
    UserDAO --> UserController --: 10.return Admin List

end

UserController -> UserDAO --++: 11.getByPage()
UserDAO --> UserController --++: 12.return Admin List
UserController --> AdminManagementPage --: 13.dispatch


@enduml