@startuml

actor       Admin
participant UserManagementPage
participant UserController
participant UserDAO
database DB

Admin -> UserController  --++: 1.Click on "Admins Management" title
UserController -> UserDAO --++: 2.getByAccess()
UserDAO -> DB --++ : 3.Query in DB
DB --> UserDAO --++: 4.return Admin List
UserDAO --> UserController --++: 5.return Admin List
UserController -> UserDAO --++: 6.getByPage()
UserDAO --> UserController --++: 7.return Admin List
UserController --> UserManagementPage --: 8.dispatch

@enduml